### ISSUE TITLE
add docker support

### ISSUE THREAD

**Issue by gilly42** [tardisx/gropple#12]
could you provide an docker file or better a docker-compose to run it as service?

**Comment by tardisx** [comment]
I certainly could, though I've avoided it so far. The existing single binary should be very easy to deploy. Being inside a container would add some complexities, the TCP port mapping and mapping a mounted volume to somewhere so that the downloaded files are available. 

In what way would it make your setup easier ?

**Comment by tardisx** [comment]
docker compose added in v1.0.0
